routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Public
 */
Route::view('/', 'index')->name('home');
Route::redirect('/menus/dinner', '/menus/menu', 302);
Route::get('menus/dirty-sodas', 'MenuController@dirtySodas')->name('menus.dirty-sodas');
Route::get('menus/{slug}', 'MenuController@show')->name('menus.show');
Route::get('hours', 'HourController@show')->name('hours');

Route::view('reviews', 'reviews.create')->name('reviews.create');
Route::post('reviews', 'ReviewController@submitNegativeReview')->name('reviews.store');
Route::view('reviews/thank-you', 'reviews.thank-you')->name('reviews.thank-you');

Route::view('contact', 'contact.form')->name('contact');
Route::post('contact', 'ContactController@send')->name('contact.send');
Route::view('contact/thank-you', 'contact.thank-you')->name('contact.thank-you');

/**
 * Auth
 */
require __DIR__ . '/auth.php';

/**
 * Cantina Club
 */
Route::group(['prefix' => 'cantina-club', 'middleware' => 'auth'], function () {
    Route::get('profile', 'ProfileController@edit')->name('cantina-club.profile');
    Route::patch('profile', 'ProfileController@update')->name('cantina-club.profile.update');

    Route::group(['middleware' => 'verified'], function () {
        Route::get('/', 'DashboardController@dashboard')->name('cantina-club');

        Route::get('points', 'PointController@index')->name('cantina-club.points');
        Route::get('verified-actions/{verifiedAction}/visit', 'PointController@visitVerifiedAction')->name('cantina-club.verified-actions.visit');

        Route::get('coupons', 'CouponController@index')->name('cantina-club.coupons');
    });
});

/**
 * Admin
 */
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'can:view-admin'], 'as' => 'admin.'], function () {
    Route::redirect('/', '/admin/menus')->name('dashboard');

    Route::resource('menus', 'MenuController', [
        'except' => ['show']
    ]);

    Route::group(['middleware' => 'can:update-hours'], function () {
        Route::get('hours/edit', 'HourController@edit')->name('hours.edit');
        Route::patch('hours', 'HourController@update')->name('hours.update');
    });

    Route::get('point-adjustments', 'Admin\PointAdjustmentController@index')->name('point-adjustments.index');
    Route::get('point-adjustments/create', 'Admin\PointAdjustmentController@create')->name('point-adjustments.create');
    Route::post('point-adjustments', 'Admin\PointAdjustmentController@store')->name('point-adjustments.store');
    Route::get('point-adjustments/users/{user}/create-from-qr-code', 'Admin\PointAdjustmentController@createFromQrCode')->name('point-adjustments.create-from-qr-code');
    Route::post('point-adjustments/users/{user}/store-from-qr-code', 'Admin\PointAdjustmentController@storeFromQrCode')->name('point-adjustments.store-from-qr-code');

    Route::group([
        'middleware' => 'can:manage-coupons',
        'prefix' => 'coupons',
        'as' => 'coupons.',
        'namespace' => 'Admin',
        'controller' => 'CouponController',
    ], function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/', 'store')->name('store');
        Route::get('{coupon}/edit', 'edit')->name('edit');
        Route::patch('{coupon}', 'update')->name('update');
        Route::delete('{coupon}', 'destroy')->name('delete');
        Route::get('{coupon}/redeem', 'getRedeem')->name('redeem');
        Route::post('{coupon}/redeem', 'postRedeem')->name('redeem.post');
        Route::get('{coupon}/send', 'getSend')->name('send');
        Route::post('{coupon}/send', 'postSend')->name('send.post');
    });

    Route::group([
        'prefix' => 'verified-actions',
        'as' => 'verified-actions.',
        'namespace' => 'Admin',
        'controller' => 'VerifiedActionController'
    ], function () {
        Route::get('/', 'index')->name('index');
        Route::middleware('can:verify-actions')->get('{verifiedAction}/verify', 'getVerify')->name('verify');
        Route::middleware('can:verify-actions')->post('{verifiedAction}/verify', 'postVerify')->name('verify.post');

        Route::group(['middleware' => 'can:manage-verified-actions'], function () {
            Route::get('create', 'create')->name('create');
            Route::post('/', 'store')->name('store');
            Route::get('{verifiedAction}/edit', 'edit')->name('edit');
            Route::patch('{verifiedAction}', 'update')->name('update');
            Route::delete('{verifiedAction}', 'destroy')->name('delete');
        });
    });

    Route::middleware(['can:manage-users'])->resource('users', 'UserController', [
        'except' => ['show']
    ]);

    /**
     * Audit Log
     */
    Route::group(['middleware' => 'can:view-audit-log', 'prefix' => 'audit-log', 'as' => 'audit-log.', 'namespace' => 'Admin'], function () {
        Route::get('/', 'AuditLogController@index')->name('index');
        Route::get('events/{auditLogEvent}/show', 'AuditLogController@show')->name('events.show');
    });
});

/**
 * Async
 */
Route::group(['prefix' => 'async', 'as' => 'async.'], function () {
    Route::get('menus/{menu}/content', 'MenuController@asyncContent')->name('menus.content');
    Route::get('members', 'UserController@asyncIndexCantinaClubMembers')->name('members.index');
});

/**
 * Redirects
 */
Route::redirect('home', '/', 301);

app/Models/Menu.php
<?php

namespace App\Models;

use stdClass;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Menu extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass-assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'slug',
        'content',
        'sort_order',
    ];

    /**
     * Return menus matching the given search string.
     */
    public function scopeSearch(Builder $query, string $value): Builder
    {
        $value = "%{$value}%";

        return $query->where(function ($query) use ($value) {
            $query->where('menus.name', 'like', $value);
            $query->orWhere('menus.slug', 'like', $value);
            $query->orWhere('menus.content', 'like', $value);
        });
    }

    /**
     * JSON decode the menu's content.
     */
    public function getContentAttribute($value): stdClass
    {
        $content = json_decode($value) ?? (object) [];

        return $content;
    }
}

app/Http/Controllers/MenuController.php
<?php

namespace App\Http\Controllers;

use App\Models\Menu;
use Illuminate\Http\Request;
use Illuminate\View\View;

class MenuController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $limit = $request->has('limit') ? max((Int) $request->input('limit'), 20) : 20;
        $offset = $request->has('offset') ? min((Int) $request->input('offset'), 0) : 0;

        $query = Menu::skip($offset)->take($limit);

        if ($request->filled('search')) {
            $query->search($request->input('search'));
        }

        $data['menus'] = $query->get();

        return view('admin.menus.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['menu'] = new Menu;

        return view('admin.menus.edit', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|string|max:32',
            'slug' => 'required|string|max:32',
            'content' => 'required|json',
            'sort_order' => 'integer',
        ]);

        $menu = Menu::create($request->only(['name', 'slug', 'content', 'sort_order']));

        audit_log(
            resource: $menu,
            event: 'Menu Created',
            summary: "{$request->user()->name} created new \"{$menu->name}\" menu.",
            data: $menu->toJson(),
        );

        return redirect("admin/menus/{$menu->id}/edit")->with('success', 'Menu successfully created.');
    }

    /**
     * Display the specified resource.
     *
     * @param  string  $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug)
    {
        $data['menu'] = Menu::where('menus.slug', $slug)->firstOrFail();

        return view('menus.show', $data);
    }

    /**
     * Display the specified resource.
     */
    public function dirtySodas(): View
    {
        $data['menu'] = Menu::where('menus.slug', 'dirty-sodas')->firstOrFail();

        return view('menus.dirty-sodas', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function edit(Menu $menu)
    {
        $data['menu'] = $menu;

        return view('admin.menus.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Menu          $menu
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Menu $menu)
    {
        $this->validate($request, [
            'name' => 'required|string|max:32',
            'content' => 'required|json',
            'sort_order' => 'integer',
        ]);

        $menu->update($request->only(['name', 'content', 'sort_order']));

        $changes = $menu->getChanges();

        if (!empty($changes)) {
            audit_log(
                resource: $menu,
                event: 'Menu Updated',
                summary: "{$request->user()->name} updated \"{$menu->name}\" menu.",
                data: $changes,
            );
        }

        return redirect("admin/menus/{$menu->id}/edit")->with('success', 'Menu successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Menu  $menu
     * @return \Illuminate\Http\Response
     */
    public function destroy(Menu $menu)
    {
        $menu->delete();

        audit_log(
            resource: $menu,
            event: 'Menu Deleted',
            summary: auth()->user()->name . " deleted \"{$menu->name}\" menu.",
        );

        return redirect(route('admin.menus.index'))->with('success', 'Menu successfully deleted.');
    }
}

resources/views/admin/menus/edit.blade.php
@extends('layouts.admin')

@section('content')
    <h1>{{ $menu->id ? 'Edit' : 'Create' }} Menu</h1>

    <hr>

    <form action="{{ $menu->id ? route('admin.menus.update', $menu) : route('admin.menus.store') }}" method="POST">
        @csrf @method($menu->id ? 'PATCH' : 'POST')

        @include('partials.alerts')

        <div class="form-group required">
            <label for="name">Name</label>

            <input id="name" name="name" type="text" value="{{ old('name') ? old('name') : $menu->name }}">
        </div>

        <div class="form-group required">
            <label for="slug">Slug</label>

            <slug value="{{ old('slug') ? old('slug') : $menu->slug }}"></slug>
        </div>

        <div class="form-group required">
            <label for="sort_order">Sort Order</label>

            <input id="sort_order" name="sort_order" type="text" value="{{ old('sort_order') ? old('sort_order') : $menu->sort_order }}">
        </div>

        <menu-editor name="content" :content="{{ json_encode($menu->content) }}"></menu-editor>

        <div class="form-group">
            <button class="button" type="submit">
                Save Menu
            </button>
        </div>
    </form>
@endsection

resources/views/admin/menus/index.blade.php
@extends('layouts.admin')

@section('content')
    <header class="admin-header">
        <h1>Menus</h1>

        <a href="{{ route('admin.menus.create') }}">
            <button class="button" type="button">
                Create Menu
            </button>
        </a>

        @include('admin.search')
    </header>

    @include('partials.alerts')

    @if (count($menus))
        <table class="resource-listing">
            <tbody>
                <tr>
                    <th>Name</th>

                    <th class="icon">View</th>

                    <th class="icon">Edit</th>

                    <th class="icon">Delete</th>
                </tr>

                @foreach ($menus as $menu)
                    <tr>
                        <td>
                            <a href="{{ route('admin.menus.edit', $menu) }}">
                                {{ $menu->name }}
                            </a>
                        </td>

                        <td class="icon">
                            <a target="_blank" href="{{ route('menus.show', [ 'slug' => $menu ]) }}">
                                <span class="fal fa-lg fa-eye"></span>
                            </a>
                        </td>

                        <td class="icon">
                            <a href="{{ route('admin.menus.edit', $menu) }}">
                                <span class="fal fa-lg fa-edit"></span>
                            </a>
                        </td>

                        <td class="icon">
                            <form action="{{ route('admin.menus.destroy', $menu) }}" method="POST" onsubmit="if (!confirm('Are you sure you want to delete the {{ $menu->name }} menu?')) return false;">
                                @csrf @method('DELETE')

                                <button type="submit">
                                    <span class="fal fa-lg fa-trash"></span>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p>There are currently no menus.</p>
    @endif
@endsection