routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/**
 * Public
 */
Route::view('/', 'index')->name('home');
Route::redirect('/menus/dinner', '/menus/menu', 302);
Route::get('menus/dirty-sodas', 'MenuController@dirtySodas')->name('menus.dirty-sodas');
Route::get('menus/{slug}', 'MenuController@show')->name('menus.show');
Route::get('hours', 'HourController@show')->name('hours');

Route::view('reviews', 'reviews.create')->name('reviews.create');
Route::post('reviews', 'ReviewController@submitNegativeReview')->name('reviews.store');
Route::view('reviews/thank-you', 'reviews.thank-you')->name('reviews.thank-you');

Route::view('contact', 'contact.form')->name('contact');
Route::post('contact', 'ContactController@send')->name('contact.send');
Route::view('contact/thank-you', 'contact.thank-you')->name('contact.thank-you');

/**
 * Auth
 */
require __DIR__ . '/auth.php';

/**
 * Cantina Club
 */
Route::group(['prefix' => 'cantina-club', 'middleware' => 'auth'], function () {
    Route::get('profile', 'ProfileController@edit')->name('cantina-club.profile');
    Route::patch('profile', 'ProfileController@update')->name('cantina-club.profile.update');

    Route::group(['middleware' => 'verified'], function () {
        Route::get('/', 'DashboardController@dashboard')->name('cantina-club');

        Route::get('points', 'PointController@index')->name('cantina-club.points');
        Route::get('verified-actions/{verifiedAction}/visit', 'PointController@visitVerifiedAction')->name('cantina-club.verified-actions.visit');

        Route::get('coupons', 'CouponController@index')->name('cantina-club.coupons');
    });
});

/**
 * Admin
 */
Route::group(['prefix' => 'admin', 'middleware' => ['auth', 'can:view-admin'], 'as' => 'admin.'], function () {
    Route::redirect('/', '/admin/menus')->name('dashboard');

    Route::resource('menus', 'MenuController', [
        'except' => ['show']
    ]);

    Route::group(['middleware' => 'can:update-hours'], function () {
        Route::get('hours/edit', 'HourController@edit')->name('hours.edit');
        Route::patch('hours', 'HourController@update')->name('hours.update');
    });

    Route::get('point-adjustments', 'Admin\PointAdjustmentController@index')->name('point-adjustments.index');
    Route::get('point-adjustments/create', 'Admin\PointAdjustmentController@create')->name('point-adjustments.create');
    Route::post('point-adjustments', 'Admin\PointAdjustmentController@store')->name('point-adjustments.store');
    Route::get('point-adjustments/users/{user}/create-from-qr-code', 'Admin\PointAdjustmentController@createFromQrCode')->name('point-adjustments.create-from-qr-code');
    Route::post('point-adjustments/users/{user}/store-from-qr-code', 'Admin\PointAdjustmentController@storeFromQrCode')->name('point-adjustments.store-from-qr-code');

    Route::group([
        'middleware' => 'can:manage-coupons',
        'prefix' => 'coupons',
        'as' => 'coupons.',
        'namespace' => 'Admin',
        'controller' => 'CouponController',
    ], function () {
        Route::get('/', 'index')->name('index');
        Route::get('/create', 'create')->name('create');
        Route::post('/', 'store')->name('store');
        Route::get('{coupon}/edit', 'edit')->name('edit');
        Route::patch('{coupon}', 'update')->name('update');
        Route::delete('{coupon}', 'destroy')->name('delete');
        Route::get('{coupon}/redeem', 'getRedeem')->name('redeem');
        Route::post('{coupon}/redeem', 'postRedeem')->name('redeem.post');
        Route::get('{coupon}/send', 'getSend')->name('send');
        Route::post('{coupon}/send', 'postSend')->name('send.post');
    });

    Route::group([
        'prefix' => 'verified-actions',
        'as' => 'verified-actions.',
        'namespace' => 'Admin',
        'controller' => 'VerifiedActionController'
    ], function () {
        Route::get('/', 'index')->name('index');
        Route::middleware('can:verify-actions')->get('{verifiedAction}/verify', 'getVerify')->name('verify');
        Route::middleware('can:verify-actions')->post('{verifiedAction}/verify', 'postVerify')->name('verify.post');

        Route::group(['middleware' => 'can:manage-verified-actions'], function () {
            Route::get('create', 'create')->name('create');
            Route::post('/', 'store')->name('store');
            Route::get('{verifiedAction}/edit', 'edit')->name('edit');
            Route::patch('{verifiedAction}', 'update')->name('update');
            Route::delete('{verifiedAction}', 'destroy')->name('delete');
        });
    });

    Route::middleware(['can:manage-users'])->resource('users', 'UserController', [
        'except' => ['show']
    ]);

    /**
     * Audit Log
     */
    Route::group(['middleware' => 'can:view-audit-log', 'prefix' => 'audit-log', 'as' => 'audit-log.', 'namespace' => 'Admin'], function () {
        Route::get('/', 'AuditLogController@index')->name('index');
        Route::get('events/{auditLogEvent}/show', 'AuditLogController@show')->name('events.show');
    });
});

/**
 * Async
 */
Route::group(['prefix' => 'async', 'as' => 'async.'], function () {
    Route::get('menus/{menu}/content', 'MenuController@asyncContent')->name('menus.content');
    Route::get('members', 'UserController@asyncIndexCantinaClubMembers')->name('members.index');
});

/**
 * Redirects
 */
Route::redirect('home', '/', 301);

app/Http/Controllers/Admin/VerifiedActionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\VerifiedActions\DeleteRequest;
use App\Http\Requests\VerifiedActions\IndexRequest;
use App\Http\Requests\VerifiedActions\StoreRequest;
use App\Http\Requests\VerifiedActions\UpdateRequest;
use App\Http\Requests\VerifiedActions\VerifyRequest;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\VerifiedAction;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\View\View;

class VerifiedActionController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index(IndexRequest $request): View
    {
        $query = VerifiedAction::withCount('users')->orderBy('name');

        if ($request->filled('search')) {
            $query->search($request->input('search'));
        }

        $data['verifiedActions'] = $query->paginate(25);

        return view('admin.verified-actions.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create(): View
    {
        $data['verifiedAction'] = new VerifiedAction;

        return view('admin.verified-actions.edit', $data);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRequest $request): RedirectResponse
    {
        $verifiedAction = VerifiedAction::create($request->safe()->toArray());

        audit_log(
            resource: $verifiedAction,
            event: 'Verified Action Created',
            summary: "{$request->user()->name} created the \"{$verifiedAction->name}\" Verified Action.",
        );

        return redirect(route('admin.verified-actions.edit', $verifiedAction))->with('success', 'Verified Action successfully created.');
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(VerifiedAction $verifiedAction): View
    {
        $data['verifiedAction'] = $verifiedAction;

        return view('admin.verified-actions.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRequest $request, VerifiedAction $verifiedAction): RedirectResponse
    {
        $verifiedAction->update($request->safe()->toArray());

        $changes = $verifiedAction->getChanges();
        if (!empty($changes)) {
            audit_log(
                resource: $verifiedAction,
                event: 'Verified Action Updated',
                summary: "{$request->user()->name} updated the \"{$verifiedAction->name}\" Verified Action.",
                data: $changes,
            );
        }

        return redirect(route('admin.verified-actions.edit', $verifiedAction))->with('success', 'Verified Action successfully updated.');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(DeleteRequest $request, VerifiedAction $verifiedAction): RedirectResponse
    {
        $verifiedAction->delete();

        audit_log(
            resource: $verifiedAction,
            event: 'Verified Action Archived',
            summary: "{$request->user()->name} archived the \"{$verifiedAction->name}\" Verified Action.",
        );

        return redirect(route('admin.verified-actions.index'))->with('success', 'Verified Action successfully archived.');
    }

    /**
     * Display the verify form.
     */
    public function getVerify(VerifiedAction $verifiedAction): View
    {
        $data['verifiedAction'] = $verifiedAction;

        return view('admin.verified-actions.verify', $data);
    }

    /**
     * Verify that the given user(s) have completed the given action.
     */
    public function postVerify(VerifyRequest $request, VerifiedAction $verifiedAction): RedirectResponse
    {
        $members = User::query()
            ->select(['users.id', 'users.first_name', 'users.last_name', 'users.email'])
            ->whereIn('users.id', $request->safe()->members)
            ->whereDoesntHave('verifiedActions', function ($query) use ($verifiedAction) {
                $query->where('verified_actions.id', $verifiedAction->id);
            })
            ->get();

        foreach ($members as $member) {
            $verifiedAction->verify($member);
        }

        audit_log(
            resource: $verifiedAction,
            event: 'Verified Action Verified',
            summary: "{$request->user()->name} verified the \"{$verifiedAction->name}\" Verified Action for {$members->count()} member(s).",
            data: $members->toJson(),
        );

        return redirect(route('admin.verified-actions.index'))->with('success', 'Member actions successfully verified.');
    }
}

resources/views/admin/verified-actions/edit.blade.php
@extends('layouts.admin')

@section('content')
    <header class="admin-header">
        <h1>
            {{ $verifiedAction->id ? 'Edit' : 'Create' }} Verified Action
        </h1>
    </header>

    <form action="{{ $verifiedAction->id ? route('admin.verified-actions.update', $verifiedAction)  : route('admin.verified-actions.store') }}" method="POST">
        @csrf @method($verifiedAction->id ? 'PATCH' : 'POST')

        @include('partials.alerts')

        <fieldset>
            <legend>Details</legend>

            <div class="form-group required">
                <label for="name">Name</label>

                <input id="name" name="name" type="text" required max="255" value="{{ old('name', $verifiedAction->name) }}">
            </div>

            <div class="form-group required">
                <label for="description">Description</label>

                <textarea id="description" name="description" rows="3" required max="255">{{ old('description', $verifiedAction->description) }}</textarea>
            </div>

            <div class="form-group">
                <label for="url">URL</label>

                <input id="url" name="url" type="url" max="255" value="{{ old('url', $verifiedAction->url) }}">
            </div>
        </fieldset>

        <fieldset>
            <legend>Settings</legend>

            <div class="form-group required">
                <label for="value">Value</label>

                <input id="value" name="value" type="number" required min="1" max="100" value="{{ old('value', $verifiedAction->value) }}">

                <p class="form-help">
                    This is how many points the member will earn if they complete this action.
                </p>
            </div>

            <div class="form-group">
                <label for="automatic">Automatic?</label>

                <select id="automatic" name="automatic">
                    <option value="0" {{ old('automatic', $verifiedAction->automatic) == 0 ? 'selected' : '' }}>No</option>

                    <option value="1" {{ old('automatic', $verifiedAction->automatic) == 1 ? 'selected' : '' }}>Yes</option>
                </select>

                <p class="form-help">
                    If set to "Yes", this action will automatically complete itself as soon as the member click the button.
                </p>
            </div>
        </fieldset>

        <button class="button" type="submit">
            Save Verified Action
        </button>
    </form>
@endsection

resources/views/admin/verified-actions/index.blade.php
@extends('layouts.admin')

@section('content')
    <header class="admin-header">
        <h1>
            Verified Actions
        </h1>

        <a href="{{ route('admin.verified-actions.create') }}">
            <button class="button" type="button">
                Create Verified Action
            </button>
        </a>

        @include('admin.search')
    </header>

    @include('partials.alerts')

    @if ($verifiedActions->count())
        <table class="resource-listing">
            <tbody>
                <tr>
                    <th>Name</th>

                    <th>Description</th>

                    <th>Value</th>

                    <th>Automatic</th>

                    <th>Members</th>

                    <th class="icon">Verify</th>

                    <th class="icon">Edit</th>

                    <th class="icon">Archive</th>
                </tr>

                @foreach ($verifiedActions as $verifiedAction)
                    <tr>
                        <td>
                            {{ $verifiedAction->name }}
                        </td>

                        <td>
                            {{ $verifiedAction->description }}
                        </td>

                        <td class="icon">
                            {{ $verifiedAction->value }}
                        </td>

                        <td class="icon">
                            <span class="{{ $verifiedAction->automatic ? 'fal fa-check' : '' }}"></span>
                        </td>

                        <td class="icon">
                            {{ $verifiedAction->users_count }}
                        </td>

                        <td class="icon">
                            <a href="{{ route('admin.verified-actions.verify', $verifiedAction) }}" title="Verify" aria-label="Verify">
                                <span class="fal fa-lg fa-check-circle"></span>
                            </a>
                        </td>

                        <td class="icon">
                            <a href="{{ route('admin.verified-actions.edit', $verifiedAction) }}" title="Edit" aria-label="Edit">
                                <span class="fal fa-lg fa-edit"></span>
                            </a>
                        </td>

                        <td class="icon">
                            <form action="{{ route('admin.verified-actions.delete', $verifiedAction) }}" method="POST" onsubmit="if (!confirm('Are you sure you want to archive the \'{{ $verifiedAction->name }}\' verified action?')) return false;" title="Archive" aria-label="Archive">
                                @csrf @method('DELETE')

                                <button type="submit">
                                    <span class="fal fa-lg fa-archive"></span>
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {{ $verifiedActions->appends(request()->all())->links() }}
    @else
        <p>No verified actions found.</p>
    @endif
@endsection

resources/views/admin/verified-actions/verify.blade.php
@extends('layouts.admin')

@section('content')
    <header class="admin-header">
        <h1>
            Verify Action
        </h1>
    </header>

    <form action="{{ route('admin.verified-actions.verify.post', $verifiedAction) }}" method="POST">
        @csrf

        @include('partials.alerts')

        <fieldset>
            <legend>Members</legend>

            <div class="form-group required">
                <label for="members">Members</label>

                <resource-filter
                    id="members"
                    name="members[]"
                    load-url="{{ route('async.members.index') }}"
                    :model-value="{{ json_encode(old('members', [])) }}"
                ></resource-filter>
            </div>
        </fieldset>

        <button class="button" type="submit">
            Verify Action
        </button>
    </form>
@endsection